---
title: "Problem-1-Probability-Practice"
author: "Deepti Hariyani-Kapish Krishna Bodapati-Yash Jain"
date: "2023-08-13"
output:
  pdf_document: default
  html_document: default
---

Part A. Visitors to your website are asked to answer a single survey question before they get access to the content on the page. Among all of the users, there are two categories: Random Clicker (RC), and Truthful Clicker (TC). There are two possible answers to the survey: yes and no. Random clickers would click either one with equal probability. You are also giving the information that the expected fraction of random clickers is 0.3. After a trial period, you get the following survey results: 65% said Yes and 35% said No. What fraction of people who are truthful clickers answered yes? Hint: use the rule of total probability

*Solution:*

The following are given:

Total probability of 'Yes' P(Yes) : 0.65

Total probability of 'No' P(No) : 0.35

Percentage of Truthful Clickers P(TC) : 0.7

Percentage of Random Clickers P(RC) : 0.3

Probability of Random Clickers clicking 'Yes' or 'No' is equal.

So, P(RC | Yes) : 0.5

  P(RC | No) : 0.5
    
Let x be that probability that a Truthful Clicker clicks 'Yes'

So, P(TC | Yes) : x

  P(TC | No) : 1-x
    
Using the rule of total probability,

P(Yes) = P(TC) X P(TC | Yes) + P(RC) X P(RC | Yes)

0.65 = 0.7x + 0.15

x = 5/7

=> Percentage of Random Clickers clicking 'Yes' is approximately 70%



Part B. Imagine a medical test for a disease with the following two attributes:

The sensitivity is about 0.993. That is, if someone has the disease, there is a probability of 0.993 that they will test positive.
The specificity is about 0.9999. This means that if someone doesn't have the disease, there is probability of 0.9999 that they will test negative.
In the general population, incidence of the disease is reasonably rare: about 0.0025% of all people have it (or 0.000025 as a decimal probability).
Suppose someone tests positive. What is the probability that they have the disease?

*Solution:*

Let us suppose that the sample population is 10,000,000,000.

As per the disease probability, 250,000 persons have disease.

Out of these 250,000, due to the sensitivity of the test, 248,250 are tested positives and the remaining 1,750 are not tested positive.

However, since the specificity of test is 0.9999, out of 999,750,000 people who don't have disease, 999,975 are tested positive. So, these 999,975 are false positives.

In total, 248,250 + 999,975 are tested positive.

So, probability of a person having disease if tested positive = 248,250/(248,250 + 999,975) = 0.2


